setopt SHARE_HISTORY
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=1000

# REPORTTIME=1
# TMOUT=1
# TRAPALRM() {
#   zle reset-prompt
# }


setopt prompt_subst
PROMPT='👤%F{magenta}%n%f 💻%F{cyan}%m%f 📁%F{white}%~%f $(prompt_git)
🐈 '
# ▓▒░ ✗
# ⚡🐍💎🐳🌟🏄🔥✨👀💡🔄📣📚📺💨🐣🐛💬🌀🚀🐯👋🏠🚫🔮🧪🤖
# 🔴🟠🟡🟢🔵🟣

function preexec() {
  timer=$(date +%s%3N)
}

function precmd() {
  vcs_info
  now=$(date +%s%3N)
  elapsed=$([ ${timer} ] && echo $((${now}-${timer})) || echo 0)
  unset timer

  ms=$((elapsed % 1000))
  s=$((elapsed / 1000 % 60))
  m=$((elapsed / 1000 / 60 % 60))
  h=$((elapsed / 1000 / 60 / 60 % 24))
  d=$((elapsed / 1000 / 60 / 60 / 24))

  exectime="${ms}%F{magenta}ms%f"
  [ ${s} -gt 0 ] && exectime="${s}%F{magenta}s%f"
  [ ${m} -gt 0 ] && exectime="${m}%F{magenta}m%f${exectime}"
  [ ${h} -gt 0 ] && exectime="${h}%F{magenta}h%f${exectime}"
  [ ${d} -gt 0 ] && exectime="${d}%F{magenta}d%f${exectime}"

  RPROMPT="%(?.%F{green}✓.%F{red}💀%?)%f ⏳%F{white}${exectime}%f 🕑%F{yellow}%D{%H:%M:%S}%f"
}

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes false
zstyle ':vcs_info:git*' formats '%b'
zstyle ':vcs_info:git*' actionformats '%b (%a)'

function prompt_git() {
  is_dirty() {
    test -n "$(git status --porcelain --ignore-submodules)"
  }
  ref="${vcs_info_msg_0_}"
  if [[ -n "${ref}" ]]; then
    if [[ "${ref/.../}" == "${ref}" ]]; then
      ref="${BRANCH}${ref}"
    else
      ref="${DETACHED}❗${ref/.../}"
    fi
    if is_dirty; then
      ref="${ref}±"
    else
      ref="${ref}"
    fi
    # prompt_segment ${color} ${PRIMARY_FG}
    print -Pn "%F{yellow}(${ref})%f"
  fi
}


### Added by Zinit's installer ###
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
  command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
  command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
    print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "${HOME}/.zinit/bin/zinit.zsh"


### Zinit Plugin ###
# zinit ice lucid wait='0' atinit='zpcompinit'
zinit light zsh-users/zsh-syntax-highlighting
# zinit light zdharma/fast-syntax-highlighting

# zinit ice lucid wait='0'
# zinit light zsh-users/zsh-completions

# zinit ice lucid wait="0" atload='_zsh_autosuggest_start; zpcompinit; zpcdreplay'
zinit light zsh-users/zsh-autosuggestions
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history)
# ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)

# autoload -Uz _zinit
# (( ${+_comps} )) && _comps[zinit]=_zinit
# 
# # Load a few important annexes, without Turbo
# # (this is currently required for annexes)
# zinit light-mode for \
#   zinit-zsh/z-a-rust \
#   zinit-zsh/z-a-as-monitor \
#   zinit-zsh/z-a-patch-dl \
#   zinit-zsh/z-a-bin-gem-node
# 
# ### End of Zinit's installer chunk
# 
# module_path+=( "/home/${USER}/.zinit/bin/zmodules/Src" )
# zmodload zdharma/zplugin
# 
# source "${HOME}/.zinit/bin/zinit.zsh"
# # zinit self-update
# # zinit update
# # zinit delete --clean
# 
# autoload -Uz compinit
# compinit
# 
# zinit cdreplay -q
# # zinit module build


### Alias ###
alias ls="ls --color=auto"
alias ssh="ssh -Y -D 0.0.0.0:800$WINDOW "
# alias ssh="ssh -Y -D `ifconfig ens37 | sed -n '2p' | awk '{print $2}'`:800$WINDOW "
